import { report } from './_harness.mjs';
await import('./imageops.test.mjs');
await import('./physics.test.mjs');
await import('./petpack.test.mjs');
await import('./zip.test.mjs');
await import('./gif.test.mjs');
await import('./segmentation.test.mjs');
await import('./models.test.mjs');
await import('./effects.test.mjs');
await import('./speech.test.mjs');
await import('./cutassess.test.mjs');
await import('./flatbg.test.mjs');
await import('./struggle.test.mjs');
await import('./sleep-look.test.mjs');
await import('./hop.test.mjs');
await import('./behavior.test.mjs');
await import('./bugchase.test.mjs');
await import('./qbody.test.mjs');
await import('./safeid.test.mjs');
await import('./budget.test.mjs');
await import('./displays.test.mjs');
await import('./motion.test.mjs');
await import('./align.test.mjs');
await import('./templates.test.mjs');
await import('./platform.test.mjs');
await import('./sharepack.test.mjs');
await import('./mytemplates.test.mjs');
await import('./autoselect.test.mjs');
await import('./dnd.test.mjs');
await import('./library.test.mjs');
await import('./tray.test.mjs');
await import('./ipc.test.mjs');
const { pass, total } = report('桌宠制作器 单元测试');
process.exit(pass === total ? 0 : 1);